// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateTransfer implements createTransfer operation.
//
// Creates an outbound transfer.
//
// POST /transferir
func (UnimplementedHandler) CreateTransfer(ctx context.Context, req *CreateTransferRequest) (r CreateTransferRes, _ error) {
	return r, ht.ErrNotImplemented
}
